jQuery(document).ready(function(){
if(jQuery("body").hasClass("i18n-zh-hant")){
			jQuery("#edit-captcha-response").attr("placeholder","輸入驗證碼");
}else if(jQuery("body").hasClass("i18n-zh-hans")){
      jQuery("#edit-captcha-response").attr("placeholder","输入验证码");
}else if(jQuery("body").hasClass("i18n-en")){
     jQuery("#edit-captcha-response").attr("placeholder","CAPTCHA");
}
if(jQuery("body").hasClass("i18n-zh-hant")){
      jQuery("#block-webform-client-block-105 .webform-submit").attr("value","提交");
}
jQuery(".facebook-con").click(function(){
     jQuery(".facebook-list").css("display","block");
     jQuery(".wechat-list").css("display","none");
});
jQuery(".wechat-con").click(function(){
     jQuery(".wechat-list").css("display","block");
     jQuery(".facebook-list").css("display","none");
});
jQuery(".wechat-sh").mouseenter(function(){
     jQuery(".img-sh").fadeIn(500);
jQuery(".wechat-sh").mouseleave(function(){
     jQuery(".img-sh").fadeOut(500);
});
});
jQuery(".wechat-zb").mouseenter(function(){
     jQuery(".img-zb").fadeIn(500);
jQuery(".wechat-zb").mouseleave(function(){
     jQuery(".img-zb").fadeOut(500);
});
});
jQuery(".wechat-hk").mouseenter(function(){
     jQuery(".img-hk").fadeIn(500);
jQuery(".wechat-hk").mouseleave(function(){
     jQuery(".img-hk").fadeOut(500);
});
});
jQuery(".wechat-bj").mouseenter(function(){
     jQuery(".img-bj").fadeIn(500);
jQuery(".wechat-bj").mouseleave(function(){
     jQuery(".img-bj").fadeOut(500);
});
});
jQuery(".wechat-gd").mouseenter(function(){
     jQuery(".img-gd").fadeIn(500);
jQuery(".wechat-gd").mouseleave(function(){
     jQuery(".img-gd").fadeOut(500);
});
});
jQuery(".wechat-fj").mouseenter(function(){
     jQuery(".img-fj").fadeIn(500);
jQuery(".wechat-fj").mouseleave(function(){
     jQuery(".img-fj").fadeOut(500);
});
});
});
